// Code generated by zek; DO NOT EDIT.

package main

import "encoding/xml"

// Kml was generated automatically.
type Kml struct {
	XMLName  xml.Name `xml:"kml"`
	Xmlns    string   `xml:"xmlns,attr"`
	Document struct {
		ID     string `xml:"id,attr"`
		Schema struct {
			Name        string `xml:"name,attr"`
			ID          string `xml:"id,attr"`
			SimpleField []struct {
				Name string `xml:"name,attr"`
				Type string `xml:"type,attr"`
			} `xml:"SimpleField"`
		} `xml:"Schema"`
		Folder struct {
			Name struct {
				Text string `xml:",chardata"`
			} `xml:"name"`
			Placemark []struct {
				Style struct {
					LineStyle struct {
						Color struct {
							Text string `xml:",chardata"`
						} `xml:"color"`
					} `xml:"LineStyle"`
					PolyStyle struct {
						Fill struct {
							Text string `xml:",chardata"`
						} `xml:"fill"`
					} `xml:"PolyStyle"`
				} `xml:"Style"`
				ExtendedData struct {
					SchemaData struct {
						SchemaUrl  string `xml:"schemaUrl,attr"`
						SimpleData []struct {
							Text string `xml:",chardata"`
							Name string `xml:"name,attr"`
						} `xml:"SimpleData"`
					} `xml:"SchemaData"`
				} `xml:"ExtendedData"`
				MultiGeometry struct {
					Polygon []struct {
						OuterBoundaryIs struct {
							LinearRing struct {
								Coordinates struct {
									Text string `xml:",chardata"`
								} `xml:"coordinates"`
							} `xml:"LinearRing"`
						} `xml:"outerBoundaryIs"`
						InnerBoundaryIs []struct {
							LinearRing struct {
								Coordinates struct {
									Text string `xml:",chardata"`
								} `xml:"coordinates"`
							} `xml:"LinearRing"`
						} `xml:"innerBoundaryIs"`
					} `xml:"Polygon"`
				} `xml:"MultiGeometry"`
			} `xml:"Placemark"`
		} `xml:"Folder"`
	} `xml:"Document"`
}
